---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pvc
  namespace: pihole 
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn  
  resources:
    requests:
      storage: 5000Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1000Mi
