# l2-policy.yaml
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ^eth[0-9]+   # match your node's actual interface name
  nodeSelector:
    matchLabels: {}
