ipam:
  mode: kubernetes

gatewayAPI:
  enabled: true

l2announcements:
  enabled: true

kubeProxyReplacement: true

# OPTIONAL (Recommended for non-kube-proxy setups):
# Uncomment and set your API Server endpoint if Cilium cannot auto-detect it
k8sServiceHost: 192.168.0.130
k8sServicePort: 6443

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
